# Generated by Django 5.1 on 2024-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='status_choices',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Client', 'Client')], default='Client', max_length=20),
        ),
    ]
