# Generated by Django 5.1 on 2024-08-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_staffs_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
